name: PR checks
on:
  pull_request:
jobs:
  test:
    name: Test using JDK ${{matrix.java}} and sbt ${{matrix.sbt}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8]
        sbt:
          - 1.8.2
          - 0.13.18
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: adopt@1.${{matrix.java}}
      - uses: actions/cache@v3
        with:
          path: ~/.ivy2/cache
          key: ivy-${{hashFiles('**/*.sbt')}}-${{matrix.sbt}}
          restore-keys: ivy-
      - uses: actions/cache@v3
        with:
          path: ~/.sbt
          key: sbt-${{hashFiles('**/*.sbt')}}-${{hashFiles('project/build.properties')}}-${{matrix.sbt}}
          restore-keys: sbt-
      - run: sbt ^^${{matrix.sbt}} test
