publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "setup-publishing"
  extends: [ .sbt ]
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0 # Full clone for sbt-dynver
  script:
  - git config --global --add safe.directory $CI_PROJECT_DIR
  - git checkout -b $CI_COMMIT_BRANCH
  - sbt "show version" ci-release
