publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "setup-publishing"
  extends: [ .sbt ]
  script:
  - sbt "show version"
  - sbt ci-release
